give @p td:adamantite_block 64
give @p td:aluminum_block 64
give @p td:black_steel_block 64
give @p td:bronze_block 64
give @p td:cobalt_block 64
give @p td:electrum_block 64
give @p td:lead_block 64
give @p td:mythril_block 64
give @p td:nickel_block 64
give @p td:platinum_block 64
give @p td:silver_block 64
give @p td:steel_block 64
give @p td:tin_block 64
give @p td:titanium_block 64
give @p td:tungsten_block 64
give @p td:uranium_block 64
give @p td:zinc_block 64
give @p td:brass_block 64