give @p fc:adamantite_block 64
give @p fc:aluminum_block 64
give @p fc:amethyst_block 64
give @p fc:black_steel_block 64
give @p fc:bronze_block 64
give @p fc:cobalt_block 64
give @p fc:electrum_block 64
give @p fc:lead_block 64
give @p fc:mythril_block 64
give @p fc:nickel_block 64
give @p fc:platinum_block 64
give @p fc:silver_block 64
give @p fc:steel_block 64
give @p fc:tin_block 64
give @p fc:titanium_block 64
give @p fc:tungsten_block 64
give @p fc:uranium_block 64
give @p fc:zinc_block 64
give @p fc:brass_block 64