
give @p td:adamantite_ingot 64
give @p td:aluminum_ingot 64
give @p td:black_steel_ingot 64
give @p td:bronze_ingot 64
give @p td:cobalt_ingot 64
give @p td:electrum_ingot 64
give @p td:lead_ingot 64
give @p td:mithril_ingot 64
give @p td:nickel_ingot 64
give @p td:platinum_ingot 64
give @p td:silver_ingot 64
give @p td:steel_ingot 64
give @p td:tin_ingot 64
give @p td:titanium_ingot 64
give @p td:tungsten_ingot 64
give @p td:uranium_ingot 64
give @p td:zinc_ingot 64
give @p td:brass_ingot 64