#bridge-file-version: #3
give @p fc:adamantite_ingot 64
give @p fc:aluminum_ingot 64
give @p fc:amethyst_ingot 64
give @p fc:black_steel_ingot 64
give @p fc:bronze_ingot 64
give @p fc:cobalt_ingot 64
give @p fc:electrum_ingot 64
give @p fc:lead_ingot 64
give @p fc:mithril_ingot 64
give @p fc:nickel_ingot 64
give @p fc:platinum_ingot 64
give @p fc:silver_ingot 64
give @p fc:steel_ingot 64
give @p fc:tin_ingot 64
give @p fc:titanium_ingot 64
give @p fc:tungsten_ingot 64
give @p fc:uranium_ingot 64
give @p fc:zinc_ingot 64
give @p fc:brass_ingot 64