give @s fc:adamantite_ore 64
give @s fc:aluminum_ore 64
give @s fc:amethyst_ore 64
give @s fc:cobalt_ore 64
give @s fc:electrum_ore 64
give @s fc:lead_ore 64
give @s fc:mythril_ore 64
give @s fc:nickel_ore 64
give @s fc:platinum_ore 64
give @s fc:silver_ore 64
give @s fc:tin_ore 64
give @s fc:titanium_ore 64
give @s fc:tungsten_ore 64
give @s fc:uranium_ore 64
give @s fc:zinc_ore 64
give @s fc:copper_ore 64